/// 设备派生黄金向量发射器（`vectors/device.json` 的生成端）。
///
/// 输出（stdout，JSON）由 Rust 侧 `rust/penguin-protocol/tests/device_vectors.rs`
/// 消费：对同一 uin + 同一随机填充，两边的派生结果必须逐字段一致。
/// ——设备派生是"同一账号恒定同一台设备"的前提，两边只要有一处不等，
/// 真机登录的指纹就会在每次实现切换时漂移。
///
/// 运行（把输出重定向到仓库的 vectors/）：
/// ```bash
/// & "$env:USERPROFILE\scoop\apps\flutter\bin\cache\dart-sdk\bin\dart.exe" `
///     run tool/qq8_device_vectors.dart > ../vectors/device.json
/// ```
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:qqclient/kernel/wlogin8/qq8_device.dart';

const int _randomFill = 0xAB;

/// 边界覆盖：奇数/偶数 uin、跨位数、u32 上限。
const List<int> _uins = <int>[10001, 10002, 999, 1234567890, 4294967295];

String _hex(List<int> b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

Map<String, Object?> _case(int uin) {
  final d = Qq8Device.generate(
    uin,
    randomBytes: (n) => Uint8List(n)..fillRange(0, n, _randomFill),
  );
  return <String, Object?>{
    'uin': uin,
    'imei': d.imei,
    'macAddress': d.macAddress,
    'guid': _hex(d.guid),
    'androidId': d.androidId,
    'bootId': d.bootId,
    'procVersion': d.procVersion,
    'ipAddress': d.ipAddress,
    'wifiSsid': d.wifiSsid,
    'fingerprint': d.fingerprint,
    'version': <String, Object?>{
      'release': d.version.release,
      'codename': d.version.codename,
      'incremental': d.version.incremental,
      'sdk': d.version.sdk,
    },
    'imsi': _hex(d.imsi),
    'tgtgt': _hex(d.tgtgt),
    'product': d.product,
    'device': d.device,
    'board': d.board,
    'brand': d.brand,
    'model': d.model,
    'bootloader': d.bootloader,
    'baseband': d.baseband,
    'sim': d.sim,
    'apn': d.apn,
    'osType': d.osType,
    'wifiBssid': d.wifiBssid,
  };
}

void main() {
  final out = <String, Object?>{
    '_note': 'GENERATED by tool/qq8_device_vectors.dart —— 勿手改。'
        '随机源用固定填充，派生结果对同一 uin 恒定；Rust 侧同名测试消费。',
    'randomFill': _randomFill.toRadixString(16).padLeft(2, '0'),
    'cases': _uins.map(_case).toList(),
  };
  stdout.write(const JsonEncoder.withIndent('  ').convert(out));
  stdout.write('\n');
}
