/// 上线注册请求体的字节级黄金向量发射器（`vectors/register.json` 的生成端）。
///
/// JCE 按**插入序**编码，所以只逐槽位比对抓不到"顺序写反"这类错误——
/// 这里把整条 body 的字节固定下来，Rust 侧
/// `rust/penguin-protocol/tests/register_selftest.rs` 逐字节比。
///
/// 运行：
/// ```bash
/// & "$env:USERPROFILE\scoop\apps\flutter\bin\cache\dart-sdk\bin\dart.exe" `
///     run tool/qq8_register_vectors.dart > ../vectors/register.json
/// ```
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:qqclient/kernel/wlogin8/qq8_device.dart';
import 'package:qqclient/kernel/wlogin8/qq8_register.dart';

/// 固定时间戳（与 `analysis/scripts/gen_pb_vector.cjs` 一致）。
const int _ts = 1700000000000;

String _hex(List<int> b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

Uint8List _hexToBytes(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

Qq8Device _device() => Qq8Device(
      product: 'piano',
      device: 'piano',
      board: 'piano',
      brand: 'Xiaomi',
      model: '25091RP04C',
      bootloader: 'unknown',
      fingerprint: 'Xiaomi/piano/piano:16/BP2A/eng:user/release-keys',
      bootId: '11111111-2222-3333-4444-555555555555',
      procVersion: 'Linux version 5.15.0',
      baseband: '',
      sim: 'T-Mobile',
      apn: 'wifi',
      osType: 'android',
      macAddress: '00:50:56:C0:00:08',
      ipAddress: '10.0.0.1',
      wifiBssid: '00:50:56:C0:00:08',
      wifiSsid: 'TP-LINK-2711',
      imei: '860000000000001',
      androidId: 'ABCDEF1234567890',
      version: const Qq8AndroidVersion(
        release: '10',
        codename: 'REL',
        incremental: '1234567',
        sdk: 29,
      ),
      imsi: Uint8List(16),
      tgtgt: Uint8List(16),
      guid: _hexToBytes('00112233445566778899aabbccddeeff'),
    );

void main() {
  final online = Qq8Register.buildBody(
    uin: 10001,
    device: _device(),
    nowMillis: _ts,
  );
  final logout = Qq8Register.buildBody(
    uin: 10001,
    device: _device(),
    logout: true,
    nowMillis: _ts,
  );

  final out = <String, Object?>{
    '_note': 'GENERATED by tool/qq8_register_vectors.dart —— 勿手改。'
        '整条 JCE body 的字节（含字段顺序）；Rust 侧 register_selftest 逐字节比。',
    'nowMillis': _ts,
    'onlineHex': _hex(online),
    'onlineLen': online.length,
    'logoutHex': _hex(logout),
    'logoutLen': logout.length,
  };
  stdout.write(const JsonEncoder.withIndent('  ').convert(out));
  stdout.write('\n');
}
